apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
type: Opaque
stringData:
  JWT_SECRET: "your-jwt-secret"
  JWT_EXPIRATION: "15m"
  REFRESH_TOKEN_SECRET: "your-refresh-token-secret"
  REFRESH_TOKEN_EXPIRATION: "7d"
