export const enum MessagePatterns {
  auth_register = 'auth.register',
  auth_login = 'auth.login',
  auth_refresh = 'auth.refresh',
  auth_verify = 'auth.verify',
  auth_profile = 'auth.profile',
  auth_change_password = 'auth.change.password',
  auth_request_password_reset = 'auth.request.password.reset',
  auth_reset_password = 'auth.reset.password',
  auth_update_email = 'auth.update.email',
  auth_verify_email = 'auth.verify.email',

  user_create = 'user.create',
  user_registration_failed = 'user.registration.failed',
  user_get = 'user.get',
  user_update_profile = 'user.update.profile',
  user_update_preferences = 'user.update.preferences',
  user_update_settings = 'user.update.settings',
  user_deactivate = 'user.deactivate',
  user_reactivate = 'user.reactivate',
  user_search = 'user.search',
  user_update_last_login = 'user.update.last.login',

  event_create = 'event.create',
  event_get = 'event.get',
  event_get_all = 'event.get.all',
  event_update = 'event.update',
  event_delete = 'event.delete',

  booking_create = 'booking.create',
  booking_get = 'booking.get',
  booking_get_user = 'booking.get.user',
  booking_update = 'booking.update',
}
