apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
type: Opaque
stringData:
  RABBITMQ_USER: "ali"
  RABBITMQ_PASSWORD: "ehive-RabbitMQ"
  RABBITMQ_DEFAULT_USER: "ali"
  RABBITMQ_DEFAULT_PASS: "ehive-RabbitMQ"