apiVersion: v1
kind: Service
metadata:
  name: auth
spec:
  type: ClusterIP
  ports:
    - port: { { .Values.services.auth.port } }
      targetPort: { { .Values.services.auth.port } }
  selector:
    app: auth
