apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  type: ClusterIP
  ports:
    - port: { { .Values.rabbitmq.port.amqp } }
      targetPort: { { .Values.rabbitmq.port.amqp } }
    - port: { { .Values.rabbitmq.port.management } }
      targetPort: { { .Values.rabbitmq.port.management } }
  selector:
    app: rabbitmq
