apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      initContainers:
        - name: wait-for-postgres
          image: busybox:1.28
          command:
            [
              "sh",
              "-c",
              "until nc -z postgres 5432; do echo waiting for postgres; sleep 2; done;",
            ]
        - name: wait-for-rabbitmq
          image: busybox:1.28
          command:
            [
              "sh",
              "-c",
              "until nc -z rabbitmq 5672; do echo waiting for rabbitmq; sleep 2; done;",
            ]
      containers:
        - name: user-service
          image: user-service
          ports:
            - containerPort: 3004
          envFrom:
            - configMapRef:
                name: postgres-config
            - secretRef:
                name: postgres-secret
            - configMapRef:
                name: rabbitmq-config
            - secretRef:
                name: rabbitmq-secret
          command: ["sh", "-c"]
          args: ["pnpm install && pnpm run start:dev user"]
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
      volumes:
        - name: src
          hostPath:
            path: ./
            type: Directory
        - name: node-modules
          emptyDir: {}
