apiVersion: v1
kind: Service
metadata:
  name: user-service-srv
spec:
  selector:
    app: user-service
  ports:
    - name: user-service
      protocol: TCP
      port: 3003
      targetPort: 3003
  type: ClusterIP
