apiVersion: v1
kind: Service
metadata:
  name: booking-service-srv
spec:
  selector:
    app: booking-service
  ports:
    - name: booking-service
      protocol: TCP
      port: 3001
      targetPort: 3001
  type: ClusterIP
